- Dockerfile
- docker-compose.yml
Provides an image which can be run for testing the application.
* Python 3.7
* Installs via requirements.txt
* Creates `django` non-root user
* Builds the schema and loads the `sample_data` fixture.
* Exposes port 8000 when run.
Build the image: `docker-compose build`
Run it: `docker run -it -p 8000:8000 terra_django`
Access: http://127.0.0.1:8000/dashboard (login required)
TODO: Add MySQL, probably some smaller refinements
> TRRA-35: Initial Docker setup - builds base dev image

- .gitignore
- .travis.yml
- .travis/build_and_test.sh
- Dockerfile
- docker-compose.yml
- docker/entrypoint.sh
- proj/settings.py
This PR also moves the code to a subdirectory of `/home/django`, and improves the static file handling done by django / whitenoise.
> TRRA-83: Mounts code in the django container, allowing more efficient dev cycle

- docker-compose.yml
The main `docker-compose.yml` file used for development no longer builds the terra image. It will pull the image with the `latest` tag and use that for running the container.
> Django service pulls terra image from Docker Hub instead of building

- .travis/docker-compose_travis_test.yml
- docker-compose.yml
With updates to the queries merged in with PR #30 we no longer require the use of MySQL 8.0 in the docker-compose files. This PR changes the configuration back to use the MySQL 5.7 image.
> Switch from MySQL 8.0 to 5.7 in db service

- Dockerfile
I encountered permissions problems when trying to run the terra container within the docker swarm cluster. The error pertains to being able to create the `/home/django/terra/static` directory. 
After some investigation, I discovered that when the bind mount is used for this directory, the permission errors go away. When I'm **not** using the bind mount, and we're trying to create the static file dir at run time from within the container, it seems this is where the permissions issue arise.
The changes made to the Dockerfile I'm hoping will ensure the terra sub-directory is created ahead of time and has the appropriate ownership before we use it as the workdir.
> Create the terra subdir and set ownership before it is set as the workdir

- .gitignore
- Dockerfile
- static/.gitignore
As a way to get around the permissions problem with creating the static subdir during container start-up, I'm going to have the static dir already exist in the repo. I realize we don't want any files that may get created in the static directory to be checked-in to the repo. So I added a .gitingore inside the static dir to prevent that from happening.
> Restore Dockerfile to previous state and include static dir

- .docker-compose_django.env
- proj/settings.py
When running within the docker swarm cluster, I am setting debug mode to false. This requires allowed hosts to be set when we are connecting via a reverse proxy (e.g. nginx).
> Parameterize allowed hosts configuration in settings.py

- .docker-compose_django.env
- docker/entrypoint.sh
- proj/settings.py
This PR removes the `--clear` from the `collectstatic` start-up routine to ensure the static file directory persists along with the .gitignore inside.
Also I put in place a fix to create the list of allowed hosts in settings.py. The env var `DJANGO_ALLOWED_HOSTS` returns a string, but the parameter in settings.py expects a list. 
I created a default list that includes `[localhost, 127.0.0.1, [::1]]`
> Allowed hosts list and prevent clearing of static files dir at start-up

- .travis/build_and_test.sh
- .travis/docker-compose_travis_test.yml
- docker-compose.yml
- proj/settings.py
- terra/management/commands/test.py
This PR overrides django's built-in 'test` command by updating mysql permissions so that the transient test database can be created.  The developer no longer needs to work around this by running a mysql command before running tests.
Some minor tweaks to the dev- and Travis-specific builds were necessary to support this, by making mysql environment variables available to the django container.  This won't be necessary in our server builds.
@sgurnick or @joshuago78 : Please review.
> TRRA-84: Allows tests to be run locally without workarounds

- Dockerfile
- docker/entrypoint.sh
This PR uses the built-in `runserver` instead of `gunicorn`, in the DEV environment.  This allows developers to see their changes immediately in the browser.
It also adds the `--reload` flag to `gunicorn`, which helped a little, but not enough, thus the switch back to `runserver`.
There may be better ways to do this, but it addresses a major need for developers now, who otherwise have to do a `docker-compose down && docker-compose up -d` after every code change in order to see changes in the browser.
@sgurnick or @joshuago78 , please review and if OK for now, merge. Thanks.
> TRRA-101: Allow developers to see code changes immediately

- terra/fixtures/sample_data.json
- terra/models.py
- terra/templates/terra/base.html
- terra/tests.py
- terra/views.py
Members of the `LBS Staff` group should have full access to all reports, but are not superusers.  This PR:
* Adds a `has_full_report_access()` function to `Employee`
* Replaces direct references to `is_superuser` with the new function in views, tests and templates
* Adds the new group to `sample_data.json`, for developers
* Updates the sample Doris account to remove superuser permission and make her a member of the group
* Adds tests verifying the group membership is correctly used
@joshuago78 Please review.
> TRRA-111: Give members of LBS Staff group full report access

- terra/admin.py
This PR:
* Adds keyword search boxes to all models, using appropriate fields like employee names, activity names, fund parts, unit names, etc.
* Removes long lists of filters from most models, generally leaving only dates and short lists.
I did not use the existing work @DRickard did on branch TRRA-79.
There's no auto-complete here.  That's better done on the admin add/edit screens. See notes on the Jira issue TRRA-79 for more context.
@joshuago78 or @DRickard Please review.
> TRRA-79: Add search boxes to all models, and remove most filters

- docker/entrypoint.sh
This fixes a problem where Docker does not pick up local changes to `requirements.txt`.  Rebuilding the image locally with `docker-compose up --build` doesn't help, it just uses (or re-pulls) the image from Docker Hub.
This changes the Docker entrypoint script so that, in the dev environment only, a fresh `pip install` is done using the local `requirements.txt`.  Most modules will already be present; this picks up anything new.
> TRRA-130: Loads local requirements.txt in dev environment when container starts

- .docker-compose_django.env
- proj/settings.py
Per the [Django email documentation](https://docs.djangoproject.com/en/2.2/topics/email/), there are a variety of email back-ends built-in to the framework for sending emails.
For a dev environment, we don't actually want to send any emails to an SMTP relay host. For this we can use Django's [console back-end](https://docs.djangoproject.com/en/2.2/topics/email/#console-backend). 
For a prod environment, where we do want to send emails, we can use Django's [smtp back-end](https://docs.djangoproject.com/en/2.2/topics/email/#smtp-backend). 
I created two new environment variables to store the email configuration:
- `DJANGO_EMAIL_BACKEND`
- `DJANGO_EMAIL_HOST`
When in a dev environment (which is the default for all o the env vars), the `DJANGO_EMAIL_BACKEND` env var will be set to …
> TRRA-135: Configuration to support email backend and smtp relay host

- proj/settings.py
When `DEFAULT_FROM_EMAIL` is not set, its default value is `webmaster@localhost`. This appears to cause errors when sending mail via the Django smtp backend. 
To remedy this, we'll set `DEFAULT_FROM_EMAIL` to `terra@library.ucla.edu`. While this isn't a real email address that anyone can reply to, it does match the library's domain and _should_ be allowed by the campus relay server.
> TRRA-135: Include config for DEFAULT_FROM_EMAIL when sending email from terra

- terra/templates/terra/employee.html
Simple change to the Employee Detail Page labels. Days OOO -> 'Days Out Working' 'Vacation Days' -> 'Days Out Vacation'. I also moved them to the end of the report to match the other report formats
> TRRA-152: Changed Days Out headings on Employee Detail Report.

- .travis/build_and_test.sh
@joshuago78 This fixes the Travis build script by preserving the return code from when the tests run.  I believe it was being lost when the next command ran (coveralls).
I tested with a fake non-zero value and the build failed as expected, so I believe this will work correctly.
After merging, rebase into your branch and push and you should get true info.
My apologies for the problem.
> TRRA-180: Preserve return value from tests, for Travis

- terra/fixtures/sample_data.json
- terra/reports.py
- terra/templates/terra/fund.html
- terra/tests.py
- terra/views.py
Updated FAU report to base spent amount on fiscal year of paid_date for actual expenses to match the Unit Report
-removed treq date in fund employee list query
-changed `alloc` to `requested`
-changed `expend` to `spent`
-removed replacement of spent expenditures for allocations 
-updated template to reflect new variable names
-updated tests
Also looks like the reformatting was picked up as changes for the unit report individual query
> Trra 177/fau report changes

- terra/fixtures/sample_data.json
- terra/templates/terra/employee_type_list.html
- terra/templates/terra/fund.html
- terra/templates/terra/unit.html
- terra/templatetags/terra_extras.py
- terra/tests.py
In unit, fau, and employee type reports:
-Adds yellow indicator if prof dev amounts are between $2800 and $3500 
-Adds red indicator if prof dev amounts are equal to or greater than $3500
-Updated sample data to include amounts that exceed $2800 and $3500
-Updated tests to match new values
Admin and prof dev days out are grouped together at the moment, so we can't isolate just prof dev days out to highlight if they are approaching the cap.
> Trra 141/color indicators

- proj/settings.py
In `settings.py`, the value of DEBUG is being interpreted as a **string** rather than a **boolean**. 
This [stack overflow article](https://stackoverflow.com/questions/38617046/django-debug-false-still-runs-in-debug-mode) provides more details. 
Summary of way to get around this:
If `DJANGO_DEBUG` is string False, then `"False" == "True"` -> `DEBUG` = False
If `DJANGO_DEBUG` is string True, then `"True" == "True"` -> `DEBUG` = True
> TRRA-192: Ensure value of DEBUG is interpreted as a boolean and not a string

- terra/admin.py
- terra/reports.py
The error occurred when the FAU report encountered a person with more than one `admin_requested` value. This was happening because the `admin_requested` and `profdev_requested` subqueries retrieved all Treqs for a given employee, not just ones with funding from the given FAU. Thus, the aggregate `Sum` function was performed on multiple FAUs for people that had trips on more than one fund. I fixed this by adding `funding__fund=fund` in the initial TravelRequest filter.
> Added filter to FAU subqueries to ensure they only retrieve TREQs for that FAU

- proj/settings.py
- proj/urls.py
- terra/context_processors.py
- terra/templates/terra/base.html
- terra/templates/terra/employee_type_list.html
- terra/templatetags/terra_extras.py
- terra/tests.py
- terra/views.py
-updated urls to specify fiscal year
-report changes data queried based on fiscal year specified in URL
-page has dropdown to select FY from inception date (previously set in settings.py)
-page defaults to current fiscal year via dictionary from new context processor to pass current fy to base template
-export is for selected FY only
-updated tests for new url structure
> Trra 186/fy change employeetype

- proj/urls.py
- terra/templates/terra/fund.html
- terra/templates/terra/fund_list.html
- terra/tests.py
- terra/views.py
-changed fund urls so fiscal year is specified in the URL
-report changes data queried based on fiscal year specified in URL
-fund page has dropdown form to select desired year
-fund page defaults to current fiscal year
-export is for selected fy
-updated tests to new fund urls
> Trra 185/fau report fiscalyear

- proj/urls.py
- terra/templates/terra/actual_expense_report.html
- terra/templates/terra/base.html
- terra/tests.py
- terra/views.py
-changed actual expense report url path to include year
-added date_paid column
-filter actual expenses based on start and end date of given fiscal year in view
-export is for selected fiscal year only
-defaults to current fiscal year from base template and context processor
-updated tests
> TRRA-197: Parameterized actual expense report.

- terra/templates/terra/unit_list.html
Changed `subunit.id` to `subsubunit.id` in link to unit detail view in line 35. Subsubunits has been linking to their parent unit instead.
> TRRA-198: Fix to unit list view bug I created. 

- terra/fixtures/sample_data.json
- terra/reports.py
- terra/templates/terra/fund.html
- terra/tests.py
- terra/views.py
TRRA-140 changes the FAU report to be list travel requests and employee aggregates for each FAU. Eventually fund managers will be able to click into treq detail pages for non-employees from this report.
-Added new fund to sample data so that a non-manager approves expenses for an employee
-Added queries to calculate type of amount spent per treq per fund
-Changed layout of FAU report template to list all employee aggregate totals then each treq the FAU was used for
-Added fund managers to list of eligible users in treq detail view
-Added tests
-Updated export to match template FAU report
> Trra 140/fau treqs

- terra/management/commands/load_employees.py
- terra/management/commands/load_travel_data.py
- terra/management/commands/load_unit_heads.py
- terra/management/commands/load_units.py
- terra/management/commands/test.py
- terra/reports.py
- terra/templatetags/terra_extras.py
- terra/tests.py
- terra/views.py
Removed various unused imports and several defined, but unused variables.
These are the remaining warnings. 
`terra/management/commands/load_travel_data.py:77:17 local variable 'funding' is assigned to but never used`
`terra/management/commands/load_travel_data.py:83:17 local variable 'act_expense' is assigned to but never used`
`terra/management/commands/load_employees.py:32:13 local variable 'employee' is assigned to but never used`
`terra/management/commands/load_employees.py:62:23 f-string is missing placeholders`
The first and third look like incorrect warnings to me as the variables are actually used later in the code. I am not sure if it makes sense to change the third warning. The last warning also seems like an unnecessary change.  Pease let me know your thoughts. Thanks
(The …
> TRRA-213: Removed imported but unused items.

- terra/templates/terra/actual_expense_report.html
- terra/tests.py
- terra/views.py
-Add UID to Actual Expense View and CSV export
-Updated a fund report test to pass in 2020 FY start and end dates specifically (hadn't noticed this was missing as it defaulted to current FY)
> TRRA 217/uid actual expense report

- .docker-compose_django.env
- charts/prod-terra-values.yaml
Fixes incorrect `csrf_trusted_origins` in Helm chart values - must be a URL!  Also fixed different, irrelevant mistake with the value in local docker-compose environment file.
Bumps version to `v1.1.1` for deployment.
> Fix CSRF_TRUSTED_ORIGINS

- .docker-compose_django.env
- Dockerfile
- README.md
- charts/prod-terra-values.yaml
- docker-compose.yml
- docker-compose_REMOTE.yml
- docker_scripts/entrypoint.sh
- requirements.txt
Implements [SYS-1669](https://uclalibrary.atlassian.net/browse/SYS-1669). Bumps version to `v1.1.4` for deployment. This application currently has no release notes template file.
This PR makes various internal changes, without affecting functionality:
* Base image now uses Debian 12 (bookworm) and Python 3.12
* Django updated to latest 4.2.x (4.2.16) security patch
* gunicorn updated to latest (23.0.0), mainly for security fixes
* Removed obsolete version declaration from `docker-compose.yml` files
* Removed obsolete non-Docker build info from `README.md`
I also found I had to change from double-quotes to single-quotes around the value of our local `DJANGO_SECRET_KEY`, because the newer `docker compose` we're using was interpreting the embedded characters `$m` in it as a environment …
> SYS-1669: Upgrade image and packages

- charts/prod-terra-values.yaml
- proj/urls.py
- requirements.txt
- terra/templates/terra/release_notes.html
- terra/views.py
Implements [SYS-1751](https://uclalibrary.atlassian.net/browse/SYS-1751)
- Updated Django to 4.2.19 to patch security issues
- Bumped Helm chart version tag
- Added release note template, view, and URL
**Testing**
✅ All automated tests passed in local development environment
[SYS-1751]: https://uclalibrary.atlassian.net/browse/SYS-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1751: Update Django to 4.2.19 to patch security issues and add release notes
