UCLALibrary/terra

- README.md
> Trra 13/readme

- .travis.yml
- README.md
> Added .travis.yml file

- terra/admin.py
- terra/models.py
- terra/tests.py
Closes TRRA-34
I did the work on this ticket without consulting with LBS, as there was simply no time to meet with them during the sprint. I think this is a good starting point. We can dd refinements in future tickets.
> Added list_display attributes for each ModelAdmin class

- .pre-commit-config.yaml
- manage.py
- proj/settings.py
- proj/urls.py
- proj/wsgi.py
- requirements.txt
- terra/admin.py
- terra/apps.py
- terra/migrations/0001_initial.py
- terra/migrations/0002_employee_uid.py
- terra/migrations/0003_employee_supervisor.py
- terra/models.py
- terra/tests.py
Ran black on existing files
These changes will require a few things once you pull them down to your local environment:
- Be sure you are running Python 3.7
- Add the new packages `$ pip install -r requirements.txt`
- Install the precommit hook `$ pre-commit install`
> Added pre-commit-config for Black

- terra/fixtures/test_employees.csv
- terra/fixtures/test_travel_data.csv
- terra/fixtures/test_units.csv
- terra/management/commands/load_employees.py
- terra/management/commands/load_travel_data.py
- terra/management/commands/load_units.py
- terra/tests.py
* TRRA-40: Add commands for loading units and employees 
* TRRA-40: Refactor handler code into separate methods
* TRRA-40: Add supervisors to employees
* TRRA-40: Add command for loading historical data (WIP)
* Activities
* Funds
* Travel Requests
@joshuago78 Can you please review this, and merge if OK?  There's more work to do here, but I'd like feedback on what I've done so far.
This code works with separately prepared CSV files - not the raw files from LBS, which are too messy as-is.  I don't want to add those to this public repo, as they contain names/emails/UIDs.
> TRRA-40: Add commands for loading data (WIP)

- terra/admin.py
Added admin filters (best-guess on desired fields) to each model.
Default right-side placement of the filter list.
Figured out how to get to TravelRequest fields to make filters on those in foreign-key objects
Found simple function to set custom labels on filters for more human-friendly display
> TRRA-63 added admin filters

- .docker-compose_db.env
- .docker-compose_django.env
- docker-compose.yml
- proj/settings.py
@akohler I made adjustments to the proj/settings.py and docker-compose.yml files to put in place support for using environment variables.
Please review when you get a chance and let me know if you see any issues with the implementation.
> TRRA-68: Support for environment variables in the django app and the MySQL DB 

- terra/models.py
- terra/reports.py
- terra/templates/terra/unit.html
OK, I have removed the recursive queries. The resulting code will end up making many more DB queries, but given our small scale, this will probably be OK.
> Trra 82/no recursive queries

- .docker-compose_django.env
- docker/entrypoint.sh
The purpose of this to conditionally run the load of sample data if the container is run in a local dev environment. We don't want to load sample data if the container is run in production.
> Create Django env variable to determine if running in dev 

- proj/urls.py
- terra/fixtures/sample_data.json
- terra/models.py
- terra/reports.py
- terra/templates/terra/fund.html
- terra/tests.py
- terra/views.py
closes TRRA-71
closes TRRA-100
> TRRA-71 Fund report

- proj/urls.py
- terra/models.py
- terra/templates/terra/base.html
- terra/templates/terra/fund_list.html
- terra/tests.py
- terra/views.py
Added list view for fund reports
Added convenience functions to test if employee is fund or unit manager
> Added menu option for fund report in site header

- terra/fixtures/lbs_staff.json
This adds a group for "LBS Staff" per TRRA-86, exported as a fixture.  Users are loaded separately.
@joshuago78 or @aprigge Please review/merge.
> TRRA-86: Define group for LBS Staff

- terra/models.py
- terra/tests.py
Closes TRRA-80
Closes TRRA-108
Closes TRRA-109
> Added default ordering for all models.

- terra/fixtures/test_employees.csv
- terra/fixtures/test_travel_data.csv
- terra/fixtures/test_units.csv
- terra/management/commands/load_employees.py
- terra/management/commands/load_travel_data.py
- terra/management/commands/load_unit_heads.py
- terra/management/commands/load_units.py
- terra/tests.py
This PR:
* Updates management commands for loading LBS data, including a new command for unit heads
* Updates tests and sample data to match
@joshuago78 or @aprigge  Please review.
> TRRA-93: Imports production-ready data

- terra/admin.py
* Employees (and managers/supervisors/approvers)
* Users
* Travel Requests
* Activities
* Funds
This is in the admin UI, on screens for adding/editing objects.
@joshuago78 or @aprigge or @DRickard : Please review.
> TRRA-115: Add autocomplete filters to long lists with free-text values:

- .travis.yml
- .travis/build_and_test.sh
- .travis/docker-compose_travis_test.yml
- Dockerfile
moved call to coveralls to the build_and_test.sh script
> Ready for merge - Coveralls integration fixed

- proj/urls.py
- terra/templates/terra/employee.html
- terra/templates/terra/treq.html
- terra/tests.py
- terra/views.py
Added TravelRequest detail page which links from the employee detail page.
> Trra 121/treq detail

- terra/templates/terra/fund_list.html
- terra/templates/terra/treq.html
- terra/templates/terra/unit_list.html
- terra/views.py
Pages enhanced:
- FAU list page
- Unit list page
- Treq detail page
I'd like to have these in production before the demo on Tuesday afternoon
> Added more Bootstrap styling to several pages

- proj/urls.py
- terra/templates/terra/unit.html
- terra/views.py
CSV download is now visible from unit reports.
> Trra 106/csv unit

- terra/reports.py
- terra/tests.py
I changed the format of the tests. All are passing for me now.
> TRRA-129: Fixes failing tests for employee type report.

- terra/templates/terra/base.html
- terra/tests.py
- terra/views.py
I've hidden the FAU report for non-LBS users.
> TRRA-145: Removed FAU report from view for non-LBS users.

- terra/templates/terra/base.html
Only shows Admin option in top right had drop down if user has full report access.
> Minor change to base template. 

- terra/templates/terra/treq.html
to match labels on employee detail page. Came up in unit head sessions.
> TRRA-155: Minor tweak to labels on treq detail page 

- terra/models.py
- terra/reports.py
- terra/templates/terra/employee.html
- terra/tests.py
- terra/views.py
-I've added a total line to the employee detail page
-Added check for only travel requests in the fiscal year for this page
-Actual expenditures replace approved amounts so with our test data where there are expenditures without approvals the approval employee total does not match what is in the column ($0 replaced with $x).
> Trra 137/employee subtotals

- terra/fixtures/sample_data.json
- terra/models.py
- terra/reports.py
- terra/tests.py
updated vsteel in fixtures, and updated tests.
> TRRA-163: Added UL employee type, updated employee type report, 

- terra/templates/terra/employee.html
- terra/templates/terra/treq.html
Removed approved column from employee detail, treq detail, and approved pills on treq tabs.
> TRRA-161 Removed approved columns and pills

- terra/templates/terra/treq.html
-Added activity location to treq detail page
> TRRA-166: Added activity location to treq detail page.

- terra/templates/terra/base.html
-Added hamburger menu for smaller viewport
-Adjusted ucla logo to be left centered, not top
-Added alt label for logo
> TRRA-164: Added hamburger menu for smaller viewports in the base.html.

- terra/templates/terra/employee.html
- terra/templates/terra/employee_type_list.html
- terra/templates/terra/treq.html
-Removed days out vacation and total from employee type report to match other reports
-Broken test here is fixed in pr #101
> Trra 174/remove days emptype

- terra/templates/terra/employee.html
- terra/templates/terra/treq.html
- terra/tests.py
-Split Employee detail page into Professional Development and Administrative tables
-Removed estimated expenses from travel request detail page Activity tab (it is already in the funding tab)
> Trra 169/split report employee

- terra/admin.py
-Employee type visible in admin UI list of employees
-Can sort by employee type
-Can filter by employee type
> Trra 150/employee type admin

- terra/admin.py
- terra/models.py
Started with a new branch post funding change
-Added Estimated Expenses and Actual Expenses inlines to TravelRequest detail in the Admin UI
-Added Estimated Expenses to TravelRequest List view
-Added method on Travel Request model for currency of total funding.
-Labels on the list view changed to be shortened. Matched estimated expense and actual expense labels with names on the inlines.
> Trra 118/treq fields admin

- README.md
Updated README, refocused on Docker environment
> TRRA-125: Update developer documentation in README.md

- terra/reports.py
- terra/templates/terra/employee.html
-Changed reports.py query to find totals of requested and spent for travel requests within the fiscal year
-Removed substitution of actual expense for approved amount
-Changed column names
> Trra 179/employee report changes

- terra/views.py
Fixes bug for unit report download.
-Updated variable names to match unit report query and template
-Updated order of items to match unit report template
-removed days out vacation and days out total to match unit repot template.
> TRRA-182: Updated variable names to match new unit report queries. 

- terra/templates/terra/treq.html
Added FAU and Date Paid columns to actual expense table in treq template.
See treq/5
> TRRA-181: Added FAU and Date Paid to actual expense table

- proj/urls.py
- terra/reports.py
- terra/templates/terra/actual_expense_report.html
- terra/templates/terra/base.html
- terra/templates/terra/employee.html
- terra/templates/terra/employee_type_list.html
- terra/templates/terra/fund.html
- terra/templates/terra/treq.html
- terra/templates/terra/unit.html
- terra/tests.py
- terra/views.py
-Add year parameter to employee url
-Updated total query for employee page to match variables (I think this had been missed previously)
-Added new function to calculate actual expenses and approved funding within given fiscal year per treq. Added to employee detail page view.
-Updated all links to employee page to new url format
-Added logic to evaluate if there are actual expenses or travel dates within the selected fiscal year within the employee report
-Removed logic that hid actual expenses until the treq had closed from treq template
-Added new test for new function
> Trra 184/fy employee

- terra/fixtures/sample_data.json
- terra/templates/terra/unit_list.html
- terra/tests.py
Allows for fourth level unit by:
-Adding fourth level unit to unit list template
-Updating sample data to include fourth level unit 
-Updating tests
> TRRA-170: Fourth level unit

- terra/reports.py
- terra/templates/terra/employee.html
- terra/templatetags/terra_extras.py
- terra/tests.py
- terra/utils.py
-Adds box on employee page to indicate remaining professional development balances
-Adds `profdev_spent` and `profdev_days_away` to `employee_total_dictionary`
-Adds `profdev_remaining` and `profdev_days_remaining` to `employee_total_report`. If days remaining is less than 0, `profdev_days_remaining` is 0.
(Feel free to suggest any styling changes too)
> Trra 158/cap remaning

- terra/tests.py
- Added explicit test for AUL access to employee outside their unit.
> TRRA-140: Added AUL test

- terra/reports.py
- terra/tests.py
-Removed lines that calculated days over prof dev cap to be 0 instead of the negative amount
-Added test for employee detail page report
> Trra 200/negative days

- terra/models.py
- terra/templates/terra/employee.html
- terra/tests.py
-Added method to employee model to determine if profdev_cap applies (Executives are AULs in TERRA)
-Added test for method and for is_UL method
-Updated template to first determine if the employee has a profdev_cap
> TRRA-202: remove balance remaining box for AUL, UL, and Other staff.

- terra/reports.py
- terra/templates/terra/employee.html
- terra/tests.py
-Add queries to `get_individual_data_employee` for profdev and admin spent and requested.
-Removed a few out of date comments about the four queries where there was more than more/less four queries
-Added two new subtotal rows to employee detail page template
-Updated tests
> Trra 199/profdev admin subtotals

- proj/urls.py
- terra/templates/terra/base.html
- terra/tests.py
- terra/views.py
-Added new url and view for org chart export
-Org chart downloads from link in nav bar added in base template
-Org chart only visible to users with full report access
-Added several tests for access
> Trra 144/pm org chart

- terra/templates/terra/employee.html
-Added cap and days cap filter to profev subtotals on the employee detail page
> TRRA-203: Added profdev cap filter to employee detail page report.

- proj/urls.py
- terra/reports.py
- terra/templates/terra/employee.html
- terra/tests.py
- terra/views.py
Adds export option for individual employee report
- Added url path and view
- Updated employee template
- Minor refactor of how days out per treq are calculated by moving it into the query and excluding any canceled treq's days_ooo from calculation (I would like to do further refactoring in another ticket)
- Updated tests
> Trra 205/employee export

- proj/urls.py
- terra/context_processors.py
- terra/templates/terra/actual_expense_report.html
- terra/templates/terra/base.html
- terra/templates/terra/employee.html
- terra/templates/terra/employee_type_list.html
- terra/templates/terra/fund.html
- terra/templates/terra/fund_list.html
- terra/templates/terra/treq.html
- terra/templates/terra/unit.html
- terra/templates/terra/unit_list.html
- terra/tests.py
- terra/views.py
Updates all reports to handle multiyear views
-updated url pattern to include a start fy and end fy
-Added `INCEPTION_YEAR` to context processor
-updated template links
-updated tests
> Trra 204/all year report

- .travis/build_and_test.sh
- README.md
- requirements.txt
* pyflakes runs with Travis
* pyflakes is available within the docker container
* README is updated to document how to run pyflakes in docker
Example: https://travis-ci.com/github/UCLALibrary/terra/builds/168442290#L997-L1020
> TRRA-211: Add pyflakes for static code analysis

- terra/templates/terra/actual_expense_report.html
- terra/views.py
-Employee type column added to Actual Expense report
-Type column added to Actual Expense export
> Trra 214/Added employee type column to actual expense report.

- terra/fixtures/sample_data.json
- terra/templates/terra/actual_expense_report.html
- terra/tests.py
- terra/views.py
-Updated sample data to include and `EXEC` type(how AULs have been categorized in TERRA)
-Updated tests
-Added AUL column to Actual Expense report
-Moved employee total to new column
-Removed all unit tables. Just one table now.
-Removed unit subtotals
> Trra 215/actual expense report changes

- .github/workflows/run_tests.yml
- docker-compose.yml
This adds a Github Action script to build and run tests when pull requests are opened.
> SYS-687: Add Github Action for running tests on pull request

- .docker-compose_db.env
- charts/Chart.yaml
- charts/prod-terra-values.yaml
- charts/templates/configmap.yaml
- charts/templates/externalsecret.yaml
- charts/templates/secrets.yaml
- charts/values.yaml
- proj/settings.py
Implements [SYS-1488](https://uclalibrary.atlassian.net/browse/SYS-1488).  Tagged as `v1.1.0` for release.
This PR primarily updates the Helm chart to make it more consistent with other team applications, and to set new values as needed for the Django 2.2 -> 4.2 upgrade and the MySQL -> PostgreSQL migration.
[SYS-1488]: https://uclalibrary.atlassian.net/browse/SYS-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1488: Update chart and values for django and db upgrade/migration

- .docker-compose_db.env
- Dockerfile
- charts/prod-terra-values.yaml
- docker-compose.yml
- docker-compose_PGADMIN.yml
- docker_scripts/entrypoint.sh
- proj/urls.py
- requirements.txt
- terra/templates/terra/base.html
- terra/templates/terra/release_notes.html
Implements [SYS-1830](https://uclalibrary.atlassian.net/browse/SYS-1830)
- upgrade Django 4.2.19 -> 5.2.1
- upgrade PostgreSQL 14 -> 16
- psycopg 2.9.7 -> 3.2.9, to go with Postgres upgrade
- upgrade Python 3.12 -> 3.13
- bump version to 1.1.6 for deployment
- update release notes
- fix issue with logout item in navbar raised in [SYS-1832](https://uclalibrary.atlassian.net/browse/SYS-1832)
Running `django-upgrade` prior to upgrade yielded no flags or changes.
Per the README, starting the containers applies migrations and loads sample data.
All 81 unit tests should pass when running `docker compose exec django python manage.py test terra`
[SYS-1830]: https://uclalibrary.atlassian.net/browse/SYS-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> Update Django and PostgreSQL
